name: Daily Email Notification

on:
  schedule:
    - cron: '0 13 * * *'  # 8 AM CST = 13:00 UTC

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Send Email Endpoint
        run: |
          curl -X POST https://url-manager-s98r.onrender.com/send-email \
            -H "X-Secret: TnxUYV4xKDTF6CnX4!wU"
