name: Daily Email Notification
 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'  # 8 AM CST during Standard Time

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Send Email Endpoint
        run: |
          curl -X POST https://url-manager-s98r.onrender.com/send-email \
            -H "X-Secret: TnxUYV4xKDTF6CnX4!wU"
